/*
 * Copyright (C) 2017 Argha Das
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package coolsd.lab.UI;

import coolsd.lab.Service.*;

/**
 *
 * @author Argha Das
 */
public class MainFrame extends javax.swing.JFrame {
    
    private MenuItemServices mi_services;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        mi_services = new MenuItemServices();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentPane = new javax.swing.JPanel();
        detailsPane = new javax.swing.JPanel();
        keyLabel = new javax.swing.JLabel();
        ssidLabel = new javax.swing.JLabel();
        ssid = new javax.swing.JLabel();
        key = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        controlPane = new javax.swing.JPanel();
        stopBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();
        showLogBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        configItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        checkUpdateItem = new javax.swing.JMenuItem();
        aboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotspot Switcher");
        setResizable(false);

        componentPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        componentPane.setEnabled(false);

        detailsPane.setBorder(javax.swing.BorderFactory.createTitledBorder("DETAILS"));

        keyLabel.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        keyLabel.setText("KEY :");
        keyLabel.setToolTipText("Key label");

        ssidLabel.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ssidLabel.setText("SSIS :");
        ssidLabel.setToolTipText("Ssid label");

        ssid.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ssid.setToolTipText("Ssid");

        key.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        key.setToolTipText("Key");

        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setToolTipText("Status");

        javax.swing.GroupLayout detailsPaneLayout = new javax.swing.GroupLayout(detailsPane);
        detailsPane.setLayout(detailsPaneLayout);
        detailsPaneLayout.setHorizontalGroup(
            detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsPaneLayout.createSequentialGroup()
                        .addComponent(ssidLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ssid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsPaneLayout.createSequentialGroup()
                        .addComponent(keyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(key, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        detailsPaneLayout.setVerticalGroup(
            detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssidLabel)
                    .addComponent(ssid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyLabel)
                    .addComponent(key))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        detailsPaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {key, keyLabel, ssid, ssidLabel});

        controlPane.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTROL"));

        stopBtn.setText("Stop");
        stopBtn.setToolTipText("Stop hotspot");

        startBtn.setText("Start");
        startBtn.setToolTipText("Start hotspot");

        showLogBtn.setText("Show Log");
        showLogBtn.setToolTipText("Show log");

        javax.swing.GroupLayout controlPaneLayout = new javax.swing.GroupLayout(controlPane);
        controlPane.setLayout(controlPaneLayout);
        controlPaneLayout.setHorizontalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(showLogBtn)
                .addContainerGap())
        );
        controlPaneLayout.setVerticalGroup(
            controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtn)
                    .addComponent(stopBtn)
                    .addComponent(showLogBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout componentPaneLayout = new javax.swing.GroupLayout(componentPane);
        componentPane.setLayout(componentPaneLayout);
        componentPaneLayout.setHorizontalGroup(
            componentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(componentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        componentPaneLayout.setVerticalGroup(
            componentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        configItem.setText("Configuration");
        configItem.setToolTipText("Configure Hotspot");
        configItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                configItemMouseReleased(evt);
            }
        });
        jMenu1.add(configItem);

        exitItem.setText("Exit");
        exitItem.setToolTipText("Close Application");
        exitItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitItemMouseReleased(evt);
            }
        });
        jMenu1.add(exitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        checkUpdateItem.setText("Check Update");
        checkUpdateItem.setToolTipText("Update Application");
        checkUpdateItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkUpdateItemMouseReleased(evt);
            }
        });
        jMenu2.add(checkUpdateItem);

        aboutItem.setText("About");
        aboutItem.setToolTipText("About Application");
        aboutItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aboutItemMouseReleased(evt);
            }
        });
        jMenu2.add(aboutItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(componentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(componentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configItemMouseReleased
        mi_services.showConfigDialog();
    }//GEN-LAST:event_configItemMouseReleased

    private void exitItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitItemMouseReleased
        mi_services.showConfirmDialog();
    }//GEN-LAST:event_exitItemMouseReleased

    private void checkUpdateItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkUpdateItemMouseReleased
        mi_services.showUpdateDialog();
    }//GEN-LAST:event_checkUpdateItemMouseReleased

    private void aboutItemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutItemMouseReleased
        mi_services.showAboutDialog();
    }//GEN-LAST:event_aboutItemMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem checkUpdateItem;
    private javax.swing.JPanel componentPane;
    private javax.swing.JMenuItem configItem;
    private javax.swing.JPanel controlPane;
    private javax.swing.JPanel detailsPane;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel key;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JButton showLogBtn;
    private javax.swing.JLabel ssid;
    private javax.swing.JLabel ssidLabel;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel status;
    private javax.swing.JButton stopBtn;
    // End of variables declaration//GEN-END:variables
}
